### ISSUE TITLE
[BUG] test_nvrpc segfaults in PingPongTest.ServerEarlyCancel test

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/MRC#34]
**Describe the bug**
This test fails with the following error:
```
[ RUN      ] PingPongTest.ServerEarlyCancel
*** Aborted at 1655308165 (unix time) try "date -d @1655308165" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x40) received by PID 10360 (TID 0x7f8e5504d000) from PID 64; stack trace: ***
    @     0x7f8e5ca80117 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f8e5c77d3c0 (unknown)
    @     0x555935387046 grpc::GenericSerialize<>()
    @     0x555935387956 nvrpc::LifeCycleStreaming<>::ForwardProgress()
    @     0x5559353899df nvrpc::LifeCycleStreaming<>::StateWriteDone()
    @     0x7f8e5cb958f2 nvrpc::Worker::ProgressEngine()
    @     0x7f8e5cb956a4 _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x7f8e5cb95cc9 std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f8e5c77a47f __pthread_once_slow
    @     0x7f8e5cb95a37 _ZNSt13__future_base11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x555935385b85 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5nvrpc14BaseThreadPoolISt5mutexSt18condition_variableE13create_threadEvEUlvE_EEEEE6_M_runEv
    @     0x7f8e5c67faa3 execute_native_thread_routine
    @     0x7f8e5c771609 start_thread
    @     0x7f8e5c4c9293 clone
Segmentation fault (core dumped)
```

From gdb the backtrace looks like:
```
Core was generated by `./tools/nvrpc/tests/test_nvrpc.x'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000555935387046 in grpc::Status grpc::GenericSerialize<grpc::ProtoBufferWriter, nvrpc::testing::Output>(google::protobuf::MessageLite const&, grpc::ByteBuffer*, bool*) ()
[Current thread is 1 (Thread 0x7f8e5504d000 (LWP 10391))]
(gdb) bt
#0  0x0000555935387046 in grpc::Status grpc::GenericSerialize<grpc::ProtoBufferWriter, nvrpc::testing::Output>(google::protobuf::MessageLite const&, grpc::ByteBuffer*, bool*) ()
#1  0x0000555935387956 in nvrpc::LifeCycleStreaming<nvrpc::testing::Input, nvrpc::testing::Output>::ForwardProgress(std::tuple<bool, bool, std::function<void ()>, bool>&) ()
#2  0x00005559353899df in nvrpc::LifeCycleStreaming<nvrpc::testing::Input, nvrpc::testing::Output>::StateWriteDone(bool) ()
#3  0x00007f8e5cb958f2 in nvrpc::Worker::ProgressEngine(int) () from /opt/conda/envs/srf/lib/libsrf_nvrpc.so
#4  0x00007f8e5cb956a4 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<nvrpc::Executor::Run()::{lambda()#1} ()>, std::allocator<int>, void ()>::_M_run()::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) () from /opt/conda/envs/srf/lib/libsrf_nvrpc.so
#5  0x00007f8e5cb95cc9 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) () from /opt/conda/envs/srf/lib/libsrf_nvrpc.so
#6  0x00007f8e5c77a47f in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x0, clockid=0, expected=0, futex_word=0x5559370e0858) at ../sysdeps/nptl/futex-internal.h:324
#7  do_futex_wait (sem=0x5559370e0858, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#8  0x0000000000000000 in ?? ()
```

**Steps/Code to reproduce bug**
```bash
cd build
./tools/nvrpc/tests/test_nvrpc.x
```

**Expected behavior**
passing

**Environment overview (please complete the following information)**
 - Environment location: Docker & conda
 - Method of SRF install: from source
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - This happens in the CI test stage, to mimic:
   - `docker run --rm -ti -v --gpus=all --cap-add=sys_nice  --network=host docker.io/gpuci/rapidsai:21.10-cuda11.4-devel-ubuntu20.04-py3.8 bash`
   - Then follow normal conda env steps

**Comment by dagardner-nv** [comment]
I was able to reproduce this in a docker build from the repo not just in the image used by ci. Test fails about 50% of the time.

**Comment by drobison00** [comment]
@dagardner-nv @ryanolson 
I'm able to generate a slightly different variant of this with clang 11/gcc 9.4 debug builds, it fails out on the DCHECK there. Looks like some kind of race.

```c++
        {
            // todo: add a CallbackOnResponseSent
            DCHECK(m_ResponseQueue.size());
            m_ResponseQueue.pop();
            m_WriteStateContext.m_NextState = &LifeCycleStreaming<RequestType, ResponseType>::StateInvalid;
        }
```

```shell
6: [ RUN      ] PingPongTest.ServerEarlyCancel
6: F20220628 15:34:16.264919 2830876 life_cycle_streaming.h:561] Check failed: m_ResponseQueue.size() 
6: *** Check failure stack trace: ***
6:     @     0x7f409d939f8d  google::LogMessage::Fail()
6:     @     0x7f409d93de67  google::LogMessage::SendToLog()
6:     @     0x7f409d939a55  google::LogMessage::Flush()
6:     @     0x7f409d93aeaa  google::LogMessageFatal::~LogMessageFatal()
6:     @           0x44e88a  nvrpc::LifeCycleStreaming<>::StateWriteDone()
6:     @           0x463cf7  nvrpc::LifeCycleStreaming<>::RunNextState()
6:     @           0x463c41  nvrpc::LifeCycleStreaming<>::StateContext<>::RunNextState()
6:     @     0x7f409da7c13a  nvrpc::IExecutor::RunContext()
6:     @     0x7f409da7be0b  nvrpc::Worker::ProgressEngine()
6:     @     0x7f409da877ef  _ZZN5nvrpc8Executor3RunEvENKUlvE_clEv
6:     @     0x7f409da877ad  _ZSt13__invoke_implIvRZN5nvrpc8Executor3RunEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
6:     @     0x7f409da8777d  _ZSt8__invokeIRZN5nvrpc8Executor3RunEvEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS5_DpOS6_
6:     @     0x7f409da87749  _ZNSt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEE6__callIvJEJEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
6:     @     0x7f409da87703  _ZNSt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEEclIJEvEET0_DpOT_
6:     @     0x7f409da876ad  _ZSt13__invoke_implIvRSt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEEJEET_St14__invoke_otherOT0_DpOT1_
6:     @     0x7f409da8767d  _ZSt10__invoke_rIvRSt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
6:     @     0x7f409da875fc  _ZZNSt13__future_base11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvENKUlvE_clEv
6:     @     0x7f409da874e9  _ZNKSt13__future_base12_Task_setterISt10unique_ptrINS_7_ResultIvEENS_12_Result_base8_DeleterEEZNS_11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvEUlvE_vEclEv
6:     @     0x7f409da87490  _ZSt13__invoke_implISt10unique_ptrINSt13__future_base7_ResultIvEENS1_12_Result_base8_DeleterEERNS1_12_Task_setterIS6_ZNS1_11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvEUlvE_vEEJEET_St14__invoke_otherOT0_DpOT1_
6:     @     0x7f409da873f1  _ZSt10__invoke_rISt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEERNS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvEUlvE_vEEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESN_E4typeEOSO_DpOSP_
6:     @     0x7f409da872c0  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFZN5nvrpc8Executor3RunEvEUlvE_vEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
6:     @     0x7f409da871e9  std::function<>::operator()()
6:     @     0x7f409da86dca  std::__future_base::_State_baseV2::_M_do_set()
6:     @           0x429e91  std::__invoke_impl<>()
6:     @           0x429d9c  std::__invoke<>()
6:     @           0x429d2c  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
6:     @           0x429cac  _ZZNSt9once_flag18_Prepare_executionC1IZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS3_12_Result_baseENS7_8_DeleterEEvEEPbEJPS4_SC_SD_EEvRS_OT_DpOT0_EUlvE_EERSI_ENKUlvE_clEv
6:     @           0x429c89  _ZZNSt9once_flag18_Prepare_executionC1IZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS3_12_Result_baseENS7_8_DeleterEEvEEPbEJPS4_SC_SD_EEvRS_OT_DpOT0_EUlvE_EERSI_ENUlvE_8__invokeEv
6:     @     0x7f409d8c94df  __pthread_once_slow
6:     @           0x429bfb  __gthread_once()
6:     @           0x429a39  std::call_once<>()
6:     @     0x7f409da86a24  std::__future_base::_State_baseV2::_M_set_result()
```

**Comment by ryanolson** [comment]
Nice catch! That should help a lot.

**Comment by ryanolson** [comment]
nvrpc has been replaced by a fibers implementation of grpc client/server for bidirectional streaming.
